### PR TITLE
Added cpplint to test env and run cpplint during Travis build

### PR DESCRIPTION
**Pull request by kchoadley**
- Cleaned up the Dockerfiles comments
- example.cpp now complies with cpplint

### CODE REVIEW

**Comment by Vaniya-Agrawal** [comment]
Looks good. Same question about the "COPY . ." though.

**Comment by kchoadley** [comment]
What specifically is your question about the "COPY . ."?
Copy in a docker file takes a source directory first then a destination directory second. In this case the first "." is the source code directory. The second directory is the current working directory in the docker container, which is defined in the previous command, WORKDIR "/usr/src/aoi"

**Comment by kchoadley** [comment]
https://docs.docker.com/engine/reference/builder/#copy

**Comment by Vaniya-Agrawal** [comment]
Gotcha, ok thanks for the explanation! All looks good to me.

**Review by Vaniya-Agrawal — APPROVED** [review]
Looks great.

**Pull request merged**
